name: Update Superliga Table

on:
  workflow_dispatch: # körs manuellt
  schedule:
    - cron: '0 0 * * *' # körs varje natt kl 00:00 UTC

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios cheerio

      - name: Fetch table
        run: node fetch_table.js

      - name: Commit and push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
